import { supabase } from './supabase';
export interface LearningClass {id:string;name:string;memberCount:number;createdAt:string}
export interface MatchHistoryRow {id:string;roomCode:string;worldName:string;status:string;gameMode:string;createdAt:string;endedAt?:string|null;playerCount:number;targetCount:number}
export interface LeaderboardRow {playerId:string;displayName:string;xp:number;level:number;totalScore:number;totalClaims:number;matchesPlayed:number}
export interface VocabularyRow {id:string;slug:string;arabic:string;transliteration?:string|null;meaningId?:string|null;meaningEn?:string|null;category?:string|null;difficulty?:string|null;points:number}
export class AdminDataService {
  private require(){if(!supabase)throw new Error('Supabase belum dikonfigurasi.');return supabase}
  async history():Promise<MatchHistoryRow[]>{const s=this.require();const {data,error}=await s.from('matches').select('id,room_code,status,game_mode,created_at,ended_at,target_count,worlds(name),match_players(role)').order('created_at',{ascending:false}).limit(30);if(error)throw error;return (data||[]).map((x:any)=>({id:x.id,roomCode:x.room_code,worldName:x.worlds?.name||'World',status:x.status,gameMode:x.game_mode,createdAt:x.created_at,endedAt:x.ended_at,playerCount:(x.match_players||[]).filter((p:any)=>p.role!=='spectator').length,targetCount:x.target_count}))}
  async classes():Promise<LearningClass[]>{const s=this.require();const {data,error}=await s.from('learning_classes').select('id,name,created_at,class_members(count)').order('name');if(error)throw error;return (data||[]).map((x:any)=>({id:x.id,name:x.name,memberCount:Number(x.class_members?.[0]?.count||0),createdAt:x.created_at}))}
  async createClass(name:string){const s=this.require();const {data,error}=await s.rpc('admin_create_class',{p_name:name});if(error)throw error;return data}
  async assignClass(classId:string,userId:string,assigned=true){const s=this.require();const {error}=await s.rpc('admin_assign_class',{p_class_id:classId,p_user_id:userId,p_assigned:assigned});if(error)throw error}
  async upsertVocabulary(input:{slug:string;arabic:string;transliteration?:string;meaningId:string;meaningEn?:string;category:string;difficulty:string;points:number}){const s=this.require();const {data,error}=await s.rpc('admin_upsert_vocabulary',{p_slug:input.slug,p_arabic:input.arabic,p_transliteration:input.transliteration||null,p_meaning_id:input.meaningId,p_meaning_en:input.meaningEn||null,p_category:input.category,p_difficulty:input.difficulty,p_points:input.points});if(error)throw error;return data}
  async mapWorldObject(worldSlug:string,objectId:string,vocabSlug:string,targetable=true){const s=this.require();const {error}=await s.rpc('admin_map_world_object',{p_world_slug:worldSlug,p_object_id:objectId,p_vocab_slug:vocabSlug,p_targetable:targetable});if(error)throw error}
  async setWorldActive(worldSlug:string,active:boolean){const s=this.require();const {error}=await s.rpc('admin_set_world_active',{p_world_slug:worldSlug,p_active:active});if(error)throw error}
  async mastery(){const s=this.require();const {data,error}=await s.from('user_world_progress').select('user_id,mastery,best_accuracy,updated_at,profiles(display_name),worlds(name)').order('updated_at',{ascending:false}).limit(60);if(error)throw error;return data||[]}
  async leaderboard(mode:'3d'|'ar'='3d',limit=20):Promise<LeaderboardRow[]>{const s=this.require();const {data,error}=await s.rpc(mode==='ar'?'get_ar_leaderboard':'get_3d_leaderboard',{p_limit:limit});if(error)throw error;return (data||[]).map((x:any)=>({playerId:x.player_id,displayName:x.display_name||'Player',xp:Number(x.xp||0),level:Number(x.level||1),totalScore:Number(x.total_score||0),totalClaims:Number(x.total_claims||0),matchesPlayed:Number(x.matches_played||0)}))}
  async vocabulary():Promise<VocabularyRow[]>{const s=this.require();const {data,error}=await s.from('vocabulary').select('id,slug,arabic,transliteration,meaning_id,meaning_en,category,difficulty,points').order('slug');if(error)throw error;return (data||[]).map((x:any)=>({id:x.id,slug:x.slug,arabic:x.arabic,transliteration:x.transliteration,meaningId:x.meaning_id,meaningEn:x.meaning_en,category:x.category,difficulty:x.difficulty,points:Number(x.points||0)}))}
}
