import { VOCAB } from '../data/vocabulary';
import type { MatchSnapshot } from '../services/realtimeTypes';
import type { AppUser } from '../services/AuthService';
import type { AdminAccount } from '../services/AdminUserService';

export type Route='splash'|'home'|'mode'|'worlds'|'world-detail'|'room'|'lobby'|'hunt3d'|'ar-check'|'ar-place'|'hunt-ar'|'result'|'review'|'progress'|'ranking'|'profile'|'settings'|'admin-dashboard'|'admin-create'|'admin-lobby'|'admin-live'|'admin-players'|'admin-analytics'|'admin-vocab'|'admin-worlds'|'admin-accounts';
export interface HuntLike { targets:any[]; score:{playerId:string;score:number;claims:number;wrong:number;combo:number;bestCombo:number}; timeLeft():number; remaining():number; ended:boolean; }
export interface UIContext {
  route:Route; hunt:HuntLike; arStatus?:{webxr:boolean;ar:boolean;hitTest:boolean;anchors:boolean}; arPlaced?:boolean;
  cloudEnabled?:boolean; user?:AppUser|null; match?:MatchSnapshot|null; connectionStatus?:string; presence?:Record<string,any[]>; accounts?:AdminAccount[]; accountsLoading?:boolean;
}
const logo='/icons/icon-192.png';
export function renderPage(c:UIContext){return c.route.startsWith('admin-')?admin(c):mobile(c)}
function shell(title:string,body:string,nav=true){return `<main class="mobile-shell"><header class="mobile-head"><button class="icon-btn" data-action="back">‹</button><div><b>${title}</b></div><img src="${logo}" class="mini-logo"></header>${body}${nav?bottomNav():''}</main>`}
function bottomNav(){return `<nav class="bottom-nav"><button data-nav="home">⌂<span>Home</span></button><button data-nav="worlds">◈<span>Worlds</span></button><button data-nav="mode">⚔<span>Battle</span></button><button data-nav="progress">▥<span>Progress</span></button><button data-nav="profile">●<span>Profile</span></button></nav>`}
function cloudBadge(c:UIContext){return `<div class="cloud-badge ${c.cloudEnabled?'on':'off'}">${c.cloudEnabled?'● Realtime Cloud':'● Demo Lokal'}${c.connectionStatus?` · ${esc(c.connectionStatus)}`:''}</div>`}
function mobile(c:UIContext){const name=esc(c.user?.name||'Player');switch(c.route){
case 'splash':return `<main class="splash"><div class="splash-inner"><img src="${logo}" class="hero-logo"><h1>Arabic Hunt <em>Battle</em></h1><h2 dir="rtl">معركة البحث عن الكلمات العربية</h2><p>Masuk memakai akun yang sudah dibuat oleh admin.</p>${cloudBadge(c)}<form class="login-form" id="login-form"><label>Username<input id="login-username" autocomplete="username" placeholder="contoh: ahmad01" required></label><label>Password<div class="password-wrap"><input id="login-password" type="password" autocomplete="current-password" placeholder="Password" required><button type="button" class="password-toggle" data-action="toggle-password" aria-label="Tampilkan password">👁</button></div></label><button class="primary" type="submit">Masuk</button></form><small>Akun dibuat dan dikelola oleh admin • PWA • Realtime Multiplayer • v0.4.1</small></div></main>`;
case 'home':return `<main class="mobile-shell no-head"><section class="home-hero"><div class="avatar">${initial(name)}</div><div><small>Welcome,</small><h2>${name}</h2><div class="level">Level 12 · 320 / 600 XP</div></div><button data-go="settings" class="icon-btn">⚙</button></section>${cloudBadge(c)}<section class="stats3"><div>🔥<b>7</b><span>Day Streak</span></div><div>★<b>142</b><span>Words</span></div><div>🏆<b>28</b><span>Wins</span></div></section><section class="continue-card"><div><small>Continue Learning</small><h3>Student Room</h3><b dir="rtl">غرفة الطالب</b><div class="progress"><i style="width:68%"></i></div></div><div class="room-emoji">🛏️📚</div></section><section class="home-grid"><button class="battle-card" data-go="mode">⚔<b>Battle</b><span>Realtime 2–8 pemain</span></button><button class="blue-card" data-go="progress">▥<b>Progress</b><span>Your Journey</span></button><button class="purple-card" data-go="ranking">🏆<b>Ranking</b><span>3D & AR</span></button></section>${bottomNav()}</main>`;
case 'mode':return shell('Choose Mode',`<section class="pad"><h2>Pilih mode kompetitif</h2><p class="muted">3D dan AR dipisahkan agar apple-to-apple.</p><button class="mode-card three" data-go="worlds"><div class="big-icon">🎮</div><h2>3D Battle</h2><p>Realtime room, target, claim, timer dan score tersinkron.</p><b>Mulai →</b></button><button class="mode-card ar" data-go="ar-check"><div class="big-icon">📱</div><h2>AR Battle</h2><p>WebXR placement aktif; multiplayer AR penuh tetap fase setelah QA 3D.</p><b>Cek perangkat →</b></button></section>`);
case 'worlds':return shell('Choose a World',`<section class="pad"><div class="world-card" data-go="world-detail"><div class="world-art">🛏️ 📚 💡</div><div><h3 dir="rtl">غرفة الطالب</h3><b>Student Room</b><p>25 targetable objects · realtime-ready</p><div class="progress"><i style="width:80%"></i></div></div></div><div class="world-card locked"><div class="world-art kitchen">🍳 🥣 🍎</div><div><h3 dir="rtl">المطبخ</h3><b>Kitchen</b><p>Planned v0.9</p></div></div></section>`);
case 'world-detail':return shell('World Detail',`<section class="hero-room"><div>🛏️　📚<br>💻　🪑　💡</div></section><section class="pad compact"><h1>Student Room</h1><h2 dir="rtl">غرفة الطالب</h2><p>Seed, daftar target, skor dan first claim diselesaikan server.</p><section class="stats3"><div>📖<b>25</b><span>Targets</span></div><div>⬡<b>50+</b><span>Objects</span></div><div>⚡<b>RT</b><span>Realtime</span></div></section><button class="primary" data-go="room">🎮 Play 3D</button><button class="green" data-go="ar-check">📱 Play AR</button></section>`);
case 'room':return roomPage(c);
case 'lobby':return lobbyPage(c);
case 'hunt3d':return huntPage(c,false);
case 'ar-check':{const s=c.arStatus||{webxr:false,ar:false,hitTest:false,anchors:false};return shell('AR Device Check',`<section class="pad ar-check"><h2>Pastikan HP siap untuk AR</h2>${check('WebXR Support',s.webxr)}${check('AR Session',s.ar)}${check('Hit Test',s.hitTest)}${check('Anchors',s.anchors)}<p class="hint">AR membutuhkan browser/perangkat WebXR kompatibel dan HTTPS.</p><button class="primary" data-go="ar-place">Continue to AR</button></section>`,false)}
case 'ar-place':return shell('Place AR Arena',`<section class="ar-place"><canvas id="pc-canvas" class="ar-canvas"></canvas><div class="reticle-ui"><i>⬡</i><b id="ar-message">${c.arPlaced?'Arena dikunci':'Tekan Start AR lalu gerakkan HP mencari meja/lantai'}</b></div><div class="ar-actions three-actions"><button class="ghost" data-action="reset-ar">↻ Reset</button><button class="primary" data-action="start-ar-session">📷 Start AR</button><button class="green" data-action="place-ar">⬡ Place</button></div><div class="hint dark">AR placement aktif. Multiplayer AR kompetitif belum digabung ke room 3D.</div></section>`,false);
case 'hunt-ar':return huntPage(c,true);
case 'result':return resultPage(c);
case 'review':return shell('Review Vocabulary',`<section class="pad"><div class="chips"><button class="active">All Words</button><button>Needs Practice</button></div>${['redBook','lamp','bag','key','ballUnderBed','chair'].map(id=>vocabRow(id)).join('')}</section>`);
case 'progress':return shell('My Progress',`<section class="pad"><section class="stats3"><div>★<b>3200</b><span>Total XP</span></div><div>📖<b>142</b><span>Words</span></div><div>🏆<b>28</b><span>Wins</span></div></section><h3>World Mastery</h3>${mastery('Student Room',80)}${mastery('Kitchen',20)}${mastery('Classroom',0)}<div class="callout">v0.4 menyimpan state match resmi di PostgreSQL sehingga reconnect dapat recovery.</div></section>`);
case 'ranking':return shell('Leaderboard',`<section class="pad"><div class="tabs"><button class="active">3D Ranking</button><button>AR Ranking</button></div><div class="podium"><span>🥈 Lina<br><b>10,320</b></span><span class="winner">👑 Omar<br><b>12,450</b></span><span>🥉 Maya<br><b>9,850</b></span></div>${['SaraLearn — 8,620','KhalidPro — 7,430','NoorPlay — 6,980','AliQuest — 6,150'].map((x,i)=>`<div class="rank-row"><b>${i+4}</b><span>${x}</span></div>`).join('')}</section>`);
case 'profile':return shell('My Profile',`<section class="pad profile"><div class="profile-top"><div class="avatar big">${initial(name)}</div><div><h2>${name}</h2><span>@${esc(c.user?.username||'player')} · ${esc(c.user?.role||'player')}</span></div></div>${cloudBadge(c)}<div class="level-card">⭐ Level 12<div class="progress"><i style="width:54%"></i></div><small>320 / 600 XP</small></div><button class="menu-row" data-action="sign-out">Sign out<span>›</span></button></section>`);
case 'settings':return shell('Settings',`<section class="pad">${['Harakat','Sound Effects','Music','Reduce Motion','Show Translation'].map((x,i)=>`<label class="toggle-row">${x}<input type="checkbox" ${i<3?'checked':''}></label>`).join('')}</section>`);
default:return ''}}

function roomPage(c:UIContext){return shell('Create / Join Room',`<section class="pad">${cloudBadge(c)}<div class="tabs"><button class="active">＋ Create Room</button><button>👥 Join Room</button></div><div class="form-stack"><label>Players<select id="create-players"><option>2</option><option selected>4</option><option>6</option><option>8</option></select></label><label>Target Objects<select id="create-targets"><option>8</option><option selected>12</option><option>15</option><option>20</option></select></label><label>Time Limit<select id="create-duration"><option value="120">2 min</option><option value="180" selected>3 min</option><option value="300">5 min</option></select></label><label>Difficulty<select id="create-difficulty"><option>easy</option><option selected>medium</option><option>hard</option></select></label></div><button class="primary" data-action="create-room">${c.cloudEnabled?'⚔ Create Realtime Room':'🎮 Start Local Demo'}</button><div class="join-box"><label>Join code</label><input id="join-code" value="" placeholder="Contoh A7K92F" maxlength="8" aria-label="Room code"><button class="ghost" data-action="join-room">Join Realtime Room</button></div><p class="hint">Jika Supabase belum dikonfigurasi, tombol create/join akan menjelaskan langkah setup.</p></section>`)}
function lobbyPage(c:UIContext){const s=c.match;if(!s)return shell('Waiting Room',`<section class="pad"><div class="ready-box">Belum ada match aktif.</div><button class="primary" data-go="room">Create / Join Room</button></section>`);const participants=s.players.filter(p=>p.role!=='spectator'),spectators=s.players.filter(p=>p.role==='spectator'),me=s.players.find(p=>p.playerId===c.user?.id),isHost=s.match.hostId===c.user?.id;const allReady=participants.length>=2&&participants.every(p=>p.ready);return shell('Waiting Room',`<section class="pad">${cloudBadge(c)}<div class="code-card"><small>ROOM CODE</small><h1>${esc(s.match.roomCode)}</h1><span>${s.match.gameMode.toUpperCase()} · ${s.match.targetCount} targets · ${s.match.durationSeconds/60} min</span></div><h3>Players (${participants.length}/${s.match.maxPlayers})</h3>${participants.map(p=>player(p.role==='host'?'👑':'👤',p.displayName,`${p.role==='host'?'Host · ':''}${p.ready?'Ready':'Not ready'}${p.connected===false?' · offline':''}`)).join('')}${spectators.length?`<h3>Spectator / Admin</h3>${spectators.map(p=>player('👁️',p.displayName,'Admin spectator')).join('')}`:''}<div class="ready-box">Seed world: ${s.match.seed}<br><small>Status: ${s.match.status}</small></div>${me?.role!=='spectator'?`<button class="${me?.ready?'ghost':'green'}" data-action="toggle-ready">${me?.ready?'Batalkan Ready':'✓ Saya Ready'}</button>`:''}${isHost?`<button class="gold" data-action="start-match" ${allReady?'':'disabled'}>⚔ Start Battle ${allReady?'':'(minimal 2 dan semua ready)'}</button>`:''}</section>`)}
function huntPage(c:UIContext,ar:boolean){const h=c.hunt;const players=[...(c.match?.players||[])].filter(p=>p.role!=='spectator').sort((a,b)=>b.score-a.score),isHost=!!c.match&&c.match.match.hostId===c.user?.id,paused=c.match?.match.status==='paused';return `<main class="hunt-shell"><div class="hunt-top">${isHost?`<button class="round" data-action="host-toggle-pause">${paused?'▶':'Ⅱ'}</button>`:'<button class="round" disabled>●</button>'}<div><small>TIME</small><b id="time-left">${fmt(h.timeLeft())}</b></div><div><small>SCORE</small><b id="score-value">${h.score.score}</b></div></div><div id="game-stage" class="game-stage"><canvas id="pc-canvas"></canvas><div class="tap-hint">${ar?'AR arena locked':'Drag rotate · pinch zoom · tap object · server validates claim'}</div><div id="countdown-overlay" class="countdown-overlay"></div></div><section class="target-sheet"><div class="target-title"><b>Find these objects</b><span id="target-progress">${h.score.claims}/${h.targets.length}</span></div><div id="targets" class="target-grid">${h.targets.map(t=>{const v=VOCAB[t.vocabId];const claimant=c.match?.players.find(p=>p.playerId===t.claimedBy);return `<div class="target-chip ${t.claimedBy?'claimed':''}" data-object="${esc(t.objectId)}"><span>${v?.arabic||esc(t.vocabId)}</span><i>${t.claimedBy?'✓':'○'}</i>${claimant?`<small>${esc(claimant.displayName)}</small>`:''}</div>`}).join('')}</div></section><div class="score-strip">${players.length?players.slice(0,4).map((p,i)=>`<span>${i===0?'👑':i+1} ${esc(p.displayName)} <b>${p.score}</b></span>`).join(''):`<span>${esc(c.user?.name||'Player')} <b id="mini-score">${h.score.score}</b></span>`}</div></main>`}
function resultPage(c:UIContext){const ranked=[...(c.match?.players||[])].filter(p=>p.role!=='spectator').sort((a,b)=>b.score-a.score);const rank=Math.max(1,ranked.findIndex(p=>p.playerId===c.user?.id)+1);return shell('Hunt Complete!',`<section class="result pad"><div class="trophy">${rank===1?'🏆':'🏅'}</div><h1>#${rank} ${rank===1?'Champion':'Finish'}</h1><div class="result-score">${c.hunt.score.score} pts</div><section class="stats3"><div>⬡<b>${c.hunt.score.claims}</b><span>Claimed</span></div><div>◎<b>${accuracy(c.hunt)}%</b><span>Accuracy</span></div><div>🔥<b>x${c.hunt.score.bestCombo}</b><span>Best Combo</span></div></section>${ranked.map((p,i)=>`<div class="rank-row"><b>${i+1}</b><span>${esc(p.displayName)}</span><strong>${p.score}</strong></div>`).join('')}<button class="primary" data-go="review">📖 Review Words</button><button class="ghost" data-go="home">⌂ Home</button></section>`)}
function setting(a:string,b:string,c:string){return `<div class="setting"><div><b>${a}</b><small>${c}</small></div><div class="stepper"><strong>${b}</strong></div></div>`}
function player(i:string,n:string,s:string){return `<div class="player-row"><span class="p-avatar">${i}</span><b>${esc(n)}</b><span>${esc(s)}</span></div>`}
function check(n:string,ok:boolean){return `<div class="check-row"><b>${n}</b><span class="${ok?'ok':'bad'}">${ok?'✓':'×'}</span></div>`}
function vocabRow(id:string){const v=VOCAB[id];return `<div class="vocab-row"><div class="vocab-icon">${v.category==='study'?'📖':'◈'}</div><div><b dir="rtl">${v.arabic}</b><span>${v.idn} · ${v.latin}</span></div><button data-speak="${id}">🔊</button></div>`}
function mastery(n:string,p:number){return `<div class="mastery"><div><b>${n}</b><span>${p}%</span></div><div class="progress"><i style="width:${p}%"></i></div></div>`}
function accuracy(h:HuntLike){const total=h.score.claims+h.score.wrong;return total?Math.round(h.score.claims/total*100):100}
function fmt(ms:number){const m=Math.max(0,Math.floor(ms/60000)),s=Math.max(0,Math.floor((ms%60000)/1000));return `${m}:${String(s).padStart(2,'0')}`}

function admin(c:UIContext){const r=c.route;const content=r==='admin-dashboard'?adminDashboard(c):r==='admin-create'?adminCreate(c):r==='admin-lobby'?adminLobby(c):r==='admin-live'?adminLive(c):r==='admin-players'?adminPlayers(c):r==='admin-accounts'?adminAccounts(c):r==='admin-analytics'?adminAnalytics():r==='admin-vocab'?adminVocab():adminWorlds();return `<main class="admin-layout"><aside class="sidebar"><div class="brand"><img src="${logo}"><div><b>Arabic Hunt Battle</b><small>Admin v0.4.1</small></div></div>${[['admin-dashboard','Dashboard'],['admin-create','Matches'],['admin-worlds','Worlds'],['admin-vocab','Vocabulary'],['admin-players','Players'],['admin-accounts','User Accounts'],['admin-analytics','Analytics']].map(([id,n])=>`<button data-go="${id}" class="${r===id?'active':''}">${n}</button>`).join('')}<div class="admin-user">👤 ${esc(c.user?.name||'Admin')}<br><small>@${esc(c.user?.username||'admin')} · ${c.cloudEnabled?'Realtime connected':'Setup mode'}</small><button class="sidebar-signout" data-action="sign-out">Sign out</button></div></aside><section class="admin-main">${content}</section></main>`}
function adminDashboard(c:UIContext){const s=c.match;return `<div class="admin-head"><div><h1>Dashboard</h1><p>Realtime multiplayer control center.</p></div><button class="primary small" data-go="admin-create">＋ Create Match</button></div>${cloudBadge(c)}<section class="kpis"><div><b>${s?.players.length||0}</b><span>Current Players</span></div><div><b>${s?.match.status||'—'}</b><span>Match Status</span></div><div><b>${s?.targets.filter(t=>!!t.claimedBy).length||0}</b><span>Claims</span></div><div><b>${c.connectionStatus||'idle'}</b><span>Realtime</span></div></section><div class="admin-grid"><section class="panel"><h3>Current Match</h3>${s?`<button class="match-row" data-go="admin-live">${esc(s.match.roomCode)} · ${esc(s.match.worldSlug)} · ${s.match.gameMode.toUpperCase()} · ${s.players.length}/${s.match.maxPlayers}<span>${s.match.status}</span></button>`:'<p>Belum ada match aktif pada browser ini.</p>'}</section><section class="panel"><h3>Quick Actions</h3><button class="primary" data-go="admin-create">Create Match</button><button class="green" data-go="admin-worlds">Manage Worlds</button><button class="ghost" data-go="admin-analytics">View Reports</button></section></div>`}
function adminCreate(c:UIContext){return `<div class="admin-head"><div><h1>Create New Match</h1><p>Server akan memilih target dan seed.</p></div></div>${cloudBadge(c)}<section class="panel form-grid"><label>Game Mode<select id="admin-mode"><option value="3d">3D Battle</option><option value="ar" disabled>AR Battle (v0.7)</option></select></label><label>World<select><option>Student Room</option></select></label><label>Number of Players<select id="admin-players"><option>2</option><option selected>4</option><option>6</option><option>8</option></select></label><label>Targets<select id="admin-targets"><option>8</option><option selected>12</option><option>15</option><option>20</option></select></label><label>Match Time<select id="admin-duration"><option value="120">2 Minutes</option><option value="180" selected>3 Minutes</option><option value="300">5 Minutes</option></select></label><label>Difficulty<select id="admin-difficulty"><option>easy</option><option selected>medium</option><option>hard</option></select></label><button class="primary span2" data-action="admin-create-room">⚔ Create Realtime Match</button></section>`}
function adminLobby(c:UIContext){const s=c.match;if(!s)return `<div class="admin-head"><h1>No Match</h1></div>`;const participants=s.players.filter(p=>p.role!=='spectator'),spectators=s.players.filter(p=>p.role==='spectator'),allReady=participants.length>=2&&participants.every(p=>p.ready);return `<div class="admin-head"><div><h1>Waiting Room</h1><p>Room code: ${esc(s.match.roomCode)}</p></div></div><div class="admin-grid"><section class="panel"><div class="big-code">${esc(s.match.roomCode)}</div><p>Student Room · ${s.match.gameMode.toUpperCase()} · ${s.match.targetCount} target · ${s.match.durationSeconds/60} min</p><p><b>${participants.length}/${s.match.maxPlayers}</b> participant · <b>${spectators.length}</b> spectator</p></section><section class="panel"><h3>Participants</h3>${participants.map(p=>`<div class="admin-player">● ${esc(p.displayName)} · ${p.ready?'Ready':'Not Ready'}</div>`).join('')||'<p>Waiting for players...</p>'}${spectators.length?`<h3>Admin / Spectator</h3>${spectators.map(p=>`<div class="admin-player">👁 ${esc(p.displayName)}</div>`).join('')}`:''}<button class="gold" data-action="start-match" ${allReady?'':'disabled'}>Start Battle</button></section></div>`}
function adminLive(c:UIContext){const s=c.match;const players=[...(s?.players||[])].filter(p=>p.role!=='spectator').sort((a,b)=>b.score-a.score);return `<div class="admin-head"><div><h1>Live Match</h1><p>${s?`${esc(s.match.worldSlug)} · ${s.match.gameMode.toUpperCase()} · ${esc(s.match.roomCode)}`:'No active match'}</p></div><div class="timer-box" id="admin-time">${fmt(c.hunt.timeLeft())}</div></div><div class="live-layout"><section class="panel map-panel"><div class="topdown"><div class="bed-block">BED</div><div class="desk-block">DESK</div><div class="shelf-block">SHELF</div><div id="admin-pose-layer"></div></div><div class="live-controls"><button data-action="admin-pause">Ⅱ Pause</button><button class="green" data-action="admin-resume">▶ Resume</button></div></section><section class="panel"><h3>Live Score</h3>${players.map((p,i)=>`<div class="score-row">${i+1} ${esc(p.displayName)} <b>${p.score}</b></div>`).join('')||'<p>Waiting for players...</p>'}<h3>Claims</h3><div class="feed">${s?.targets.filter(t=>t.claimedBy).slice(-7).reverse().map(t=>`${esc(s.players.find(p=>p.playerId===t.claimedBy)?.displayName||'Player')} found ${esc(t.arabic)}`).join('<br>')||'No claims yet'}</div></section></div>`}
function adminPlayers(c:UIContext){const s=c.match;return `<div class="admin-head"><div><h1>Player Monitor</h1><p>Presence, score, wrong taps dan connection.</p></div></div>${table(['Player','Role','Ready','Score','Claims','Wrong Taps'],(s?.players||[]).map(p=>[p.displayName,p.role,p.ready?'Ready':'No',String(p.score),String(p.claims),String(p.wrongTaps)]))}`}

function adminAccounts(c:UIContext){const accounts=c.accounts||[];return `<div class="admin-head"><div><h1>User Accounts</h1><p>Admin membuat username dan password. Pengguna tidak perlu Google atau Guest.</p></div></div>${cloudBadge(c)}<div class="admin-grid account-grid"><section class="panel"><h3>＋ Buat Akun</h3><div class="form-stack admin-account-form"><label>Username<input id="account-username" autocomplete="off" placeholder="contoh: ahmad01" maxlength="32"></label><label>Nama Tampilan<input id="account-display-name" autocomplete="off" placeholder="Ahmad"></label><label>Password<div class="password-wrap light"><input id="account-password" type="password" autocomplete="new-password" placeholder="Minimal 8 karakter"><button type="button" class="password-toggle" data-action="toggle-account-password">👁</button></div></label><label>Role<select id="account-role"><option value="player" selected>Player</option><option value="admin">Admin</option></select></label><button class="primary" data-action="admin-create-user">Buat Akun</button><p class="hint">Password tidak disimpan di tabel profil. Supabase Auth menyimpan hash password; aplikasi hanya menggunakan username saat login.</p></div></section><section class="panel account-list"><div class="account-list-head"><h3>Daftar Akun</h3><button class="ghost smallish" data-action="refresh-accounts">↻ Refresh</button></div>${c.accountsLoading?'<p>Memuat akun...</p>':accounts.length?accounts.map(a=>`<div class="account-row"><div class="account-avatar">${initial(a.displayName)}</div><div class="account-meta"><b>${esc(a.displayName)}</b><span>@${esc(a.username)} · ${esc(a.role)}</span><small>Level ${a.level} · ${a.xp} XP · ${a.active?'Aktif':'Nonaktif'}</small></div><div class="account-actions"><button data-action="reset-user-password" data-user-id="${a.id}" data-user-name="${esc(a.username)}">Reset Password</button><button class="${a.active?'danger-soft':'green-soft'}" data-action="toggle-user-active" data-user-id="${a.id}" data-active="${a.active?'1':'0'}">${a.active?'Nonaktifkan':'Aktifkan'}</button></div></div>`).join(''):'<p>Belum ada akun.</p>'}</section></div>`}

function adminAnalytics(){return `<div class="admin-head"><div><h1>Learning Analytics</h1><p>Fondasi analytics v0.4 — data claim tersimpan permanen.</p></div></div><section class="kpis"><div><b>✓</b><span>Claims persisted</span></div><div><b>✓</b><span>Wrong taps persisted</span></div><div><b>✓</b><span>Per-player score</span></div><div><b>v0.8</b><span>Full analytics</span></div></section>`}
function adminVocab(){return `<div class="admin-head"><div><h1>Vocabulary Manager</h1><p>Student Room vocabulary seeded ke PostgreSQL.</p></div></div>${table(['Arabic','Meaning','Category','Difficulty','Points'],Object.values(VOCAB).slice(0,15).map(v=>[v.arabic,v.en,v.category,v.difficulty,String(v.points)]))}`}
function adminWorlds(){return `<div class="admin-head"><div><h1>World Manager</h1><p>World objects menjadi sumber target server.</p></div></div><div class="world-admin-grid"><div class="world-admin"><div>🛏️📚💻</div><h3>Student Room</h3><p>Published · 25 targetable server objects</p><div class="progress"><i style="width:90%"></i></div></div><div class="world-admin disabled"><div>🍳🥣🍎</div><h3>Kitchen</h3><p>Planned v0.9</p></div></div>`}
function table(headers:string[],rows:string[][]){return `<section class="panel table-wrap"><table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></section>`}
function esc(x:any){return String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]!))}
function initial(s:string){return (s.trim()[0]||'P').toUpperCase()}
